config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :edit, :update, :show] do
    get "/change_password" => "users#change_password"
  end
  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection
    get :forgot_password, on: :collection
  end

  resources :auctions do
    resources :bids, only: [:create]
    resources :publishings, only: [:create]
  end

  resources :bids, only: [:index]

  root "auctions#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #

    can :create, Bid
    cannot :create, Bid, auction: {user: user}

    can :manage, Auction, user_id: user.id
  end
end

app/models/auction.rb
class Auction < ActiveRecord::Base
  include AASM
  belongs_to :user
  has_many :bids

  validates :title, presence: true
  validates :end_date, presence: true
  validates :reserve_price, presence: true

  aasm whiny_transitions: false do
    state :draft, initial: true
    state :published
    state :cancelled
    state :won
    state :reserve_not_met
    state :reserve_met

    event :publish do
      transitions from: :draft, to: :published
    end

    event :win do
      transitions from: :published, to: :won
    end

    event :cancel do
      transitions from: [:draft, :published, :won], to: :cancelled
    end

    event :meet_reserve do
      transitions from: :published, to: :reserve_met
    end
  end

  # for multiples? makes sense to have these separate
  # aasm(:reserve, whiny_transitions: false) do
  #   state :reserve_not_met, initial: true
  #   state :reserve_met
  #
  #   event :meet_reserve do
  #     transitions from: :reserve_not_met, to: :reserve_met
  #   end
  # end

  def published
    where(aasm_state: :published)
  end
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :auction
  belongs_to :user

  validates :amount, presence: true, numericality: {greater_than: :auction_current}


  def auction_current
    auction.current_price
  end

  def auction_title
    auction.title
  end

  def user_full_name
    user.full_name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :auctions, dependent: :destroy
  has_many :bids, dependent: :destroy

  validates :password, length: {minimum: 6}, on: :create
  validates :first_name, presence: true, on: :create
  validates :last_name, presence: true, on: :create
  validates :email, presence: true, uniqueness: true,
            format:  /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
            on: :create

  def full_name
    "#{first_name} #{last_name}".titleize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def sign_in(user)
    session[:user_id] = user.id
  end

  def user_signed_in?
    session[:user_id].present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if user_signed_in?
  end
  helper_method :current_user

  def authenticate_user
    redirect_to new_session_path, notice: "Please sign in." unless user_signed_in?
  end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create]
  before_action :find_auction, only: [:show]

  def new
    @auction = Auction.new
  end

  def create
    @auction = Auction.new auction_params
    @auction.user = current_user
    if @auction.save
      redirect_to @auction, notice: "Auction created successfully."
    else
      flash[:alert] = "Auction not created!"
      render :new
    end
  end

  def show
    @bid = Bid.new(auction: @auction)
    @bids = @auction.bids
  end

  def index
    @auctions = Auction.all
  end

  private

  def find_auction
    @auction = Auction.find params[:id]
    @auction = @auction.decorate
  end

  def auction_params
    params.require(:auction).permit(:title, :details, :end_date, :reserve_price)
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :authenticate_user, only: [:create, :index]
  def new
  end

  def create
    @bid = Bid.new bid_params
    @auction = Auction.find(params[:auction_id])
    @bid.auction = @auction
    @bid.user = current_user
    respond_to do |format|
      if @bid.save
        update_auction
        @auction = @auction.decorate
        format.html {redirect_to @auction, notice: "Bid submitted!"}
        format.js {render :create_success}
      else
        format.html { flash[:alert] = "Bid not created!"
                      redirect_to @auction }
        format.js {render :create_failure}
      end
    end
  end

  def index
    @bids = current_user.bids
  end

  private

  def bid_params
    params.require(:bid).permit(:amount)
  end

  def update_auction
    @auction.current_price = @bid.amount
    if @bid.amount >= @auction.reserve_price
      @auction.meet_reserve
    end
    @auction.save
  end
end

app/controllers/publishings_controller.rb
class PublishingsController < ApplicationController
  before_action :authenticate_user

  def create
    auction = current_user.auctions.find params[:auction_id]
    service = Auctions::PublishAuction.new(auction: auction)

    if service.call
      redirect_to auction, notice: "Published!"
    else
      redirect_to auction, alert: "Can't publish! Published already?"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email params[:email]
    cookies[:attempts] ||= 1
    if user && user.authenticate(params[:password])
      sign_in(user)
      redirect_to root_path, notice: "Sign in successful!"
    elsif cookies[:attempts].to_i >= 3
      redirect_to new_password_reset_path, alert: "Account locked! Please reset password."
    else
      flash[:alert] = "Wrong credentials!"
      current_attempts = cookies[:attempts].to_i
      current_attempts += 1
      cookies[:attempts] = current_attempts
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    cookies[:attempts] = nil
    redirect_to root_path, notice: "You are logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :change_password, :check_password]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      sign_in(@user)
      redirect_to root_path, notice: "Sign up successful!"
    else
      flash[:alert] = "Sign up unsuccessful."
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if check_password
      if @user.update user_params
        redirect_to user_path(@user), notice: "Profile updated successfully."
      else
        flash[:notice] = "Profile not updated."
        @changing_password ? (render :change_password) : (render :edit)
      end
    else
      flash[:alert] = "Wrong credentials!"
      @changing_password ? (render :change_password) : (render :edit)
    end
  end

  def change_password
  end

  private

  def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def find_user
    @user = User.find current_user.id
  end

  def check_password
    authentic_password = @user.authenticate(params[:user]["current_password"])
    different_password = params[:user]["current_password"] != params[:user]["password"]
    @changing_password = params[:user]["password"]
    @changing_password ? (authentic_password && different_password) : authentic_password
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
  def format_date_time(datetime)
    datetime.strftime("%Y-%B-%d %H:%M")
  end
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/publishings_helper.rb
module PublishingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auctions/_form.html.erb
<%= simple_form_for @auction do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.input :end_date, as: :string, input_html: { class: "datepicker" } %>
  <%= f.input :reserve_price, as: :string %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('input.datepicker').data({behaviour: "datepicker"}).datepicker({ format: 'yyyy-mm-dd' });
  });
</script>

app/views/auctions/index.html.erb
<h1>All Auctions</h1>

<% @auctions.each do |auction| %>
<div class="well">
  <h3><%= link_to auction.title, auction %></h3>
</div>
<% end %>

app/views/auctions/new.html.erb
<h1>Create Auction</h1>

<%= render 'form' %>

app/views/auctions/show.html.erb
<h1><%= @auction.title %></h1>

<p><%= @auction.details %></p>
<%= @auction.state_label %>
<br><br>
<%# this doesn't work and i have no idea why  %>
<% if can? :manage, @auction %>
<%= @auction.publish_button %>
<% end %>
<p>End Date: <%= @auction.end_date %></p>
<p>Reserve Price: <%= @auction.reserve_price %></p>
<p id="current_price">Current Price: <%= @auction.current_price %></p>

<div class="col-sm-6">
<h2>Bids:</h2>
  <%= render "bids/all_bids" %>
</div>

<% if can? :create, @bid %>
<div class="col-sm-6">
<h2>Create Bid: </h2>
  <%= render "bids/form" %>
</div>
<% end %>

app/views/bids/_all_bids.html.erb
<div id="bids">
  <% @bids.each do |bid| %>
  <p id="<%= dom_id(bid) %>"><%= number_to_currency(bid.amount) %> on <%= bid.created_at.strftime("%D")%> by <%= bid.user_full_name %></p>
  <% end %>
</div>

app/views/bids/_bid.html.erb
<p id="<%= dom_id(bid) %>"><%= number_to_currency(bid.amount) %> on <%= bid.created_at.strftime("%D")%> by <%= bid.user_full_name %></p>

app/views/bids/_form.html.erb
<div id="bid-form">
  <%= simple_form_for [@auction, @bid] do |f| %>
    <%= f.input :amount, as: :string %>
    <%= f.submit class: "btn btn-primary bid-submit" %>
  <% end %>
</div>

<script>
  $(document).ready(function(){
    $("input.bid-submit").click(function(event){
      event.preventDefault();
      $.ajax({
        type: "POST",
        url: $("div#bid-form form").attr("action"),
        data: { bid: { amount: $("input#bid_amount").val() } },
        dataType: "script",
        success: function(data) {
          return true
        },
        error: function(data) {
          return false
        }
      })
    });
  });
</script>

app/views/bids/create_failure.js.erb
alert("You cannot bid lower than the current price!");

app/views/bids/create_success.js.erb
$("<%= j render 'bid', bid: @bid %>").appendTo("#bids").hide().fadeIn(500);
$("#current_price").html("Current Price: <%= j @auction.current_price %>");
$("#state").replaceWith("<%= j @auction.state_label %>");
<% @bid = Bid.new %>
$("#bid-form").html("<%= j render 'form', bid: @bid %>");

app/views/bids/index.html.erb
<h1>Your Bids</h1>
<% @bids.each do |bid| %>
  <div class="well">
    <h3><%= number_to_currency(bid.amount) %> on <%= bid.auction_title %> at <%= bid.created_at.strftime("%D") %></h3>
    <p>Current Auction Price for <%= bid.auction_title %>: <%= number_to_currency(bid.auction_current) %></p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biddr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="col-sm-12">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "All Auctions", auctions_path %></li>
            <% if user_signed_in? %>
            <li><%= link_to "Your Bids", bids_path %></li>
            <li><%= link_to "New Auction", new_auction_path %></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Welcome #{current_user.first_name} #{current_user.last_name}!", user_path(current_user) %></li>
              <li><%= link_to "Log Out", sessions_path, method: :delete, data: {confirm: "Are you sure you want to log out?"} %></li>
            <% else %>
              <li><%= link_to "Sign In", new_session_path %></li>
              <li><button class="btn btn-default navbar-btn"><%= link_to "Sign Up", new_user_path %></button></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>

  <div class="container-fluid">
    <% if notice %>
      <div class="alert alert-success"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger"><%= alert %></div>
    <% end %>
  </div>

<div class="container-fluid"><div class="col-sm-12"><%= yield %></div></div>

</body>
</html>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <% if user_signed_in?%>
    <%= f.input :current_password %>
  <% else %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
  <% end %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/users/change_password.html.erb
<h1>Change Password</h1>

<%= form_for @user do |f| %>
  <%= content_tag(:div, class: "form-group") do %>
    <%= f.label :current_password %>
    <%= f.password_field :current_password, class: "form-control" %>
  <% end %>
  <%= content_tag(:div, class: "form-group") do %>
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  <% end %>
  <%= content_tag(:div, class: "form-group") do %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  <% end %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= render "form" %>

<%= link_to "Change Password", user_change_password_path(@user) %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "form" %>

app/views/users/show.html.erb
<h1>Your Profile</h1>

<p>First Name: <%= @user.first_name %></p>
<p>Last Name: <%= @user.last_name %></p>
<p>Email: <%= @user.email %></p>

<%= link_to "Edit Profile", edit_user_path(@user) %>